### ISSUE TITLE
Dev server crashes on SCSS error

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#4550]
If you have an SCSS compilation error, the dev server crashes. Can it just log the error and abort the compilation versus crashing the server? cc @dgutride @evwilkin @jschuler 

```
Compiled src/patternfly/components/MultipleFileUpload/multiple-file-upload.scss src/patternfly/patternfly.scss
Problem in src/patternfly/components/MultipleFileUpload/multiple-file-upload.scss: Error: expected ";".
   ╷
58 │   grid-template-columns: max-content;
   │                        ^
   ╵
  src/patternfly/components/MultipleFileUpload/multiple-file-upload.scss 58:24  root stylesheet
[15:11:32] 'watchSrcSASS' errored after 1.35 h
[15:11:32] TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (fs.js:1517:5)
    at DestroyableTransform._transform (/Users/cmichael/repos/patternfly/scripts/gulp/sass.js:59:10)
    at DestroyableTransform.Transform._read (/Users/cmichael/repos/patternfly/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/cmichael/repos/patternfly/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/Users/cmichael/repos/patternfly/node_modules/readable-stream/lib/_stream_writable.js:428:64)
    at writeOrBuffer (/Users/cmichael/repos/patternfly/node_modules/readable-stream/lib/_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (/Users/cmichael/repos/patternfly/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at DestroyableTransform.ondata (/Users/cmichael/repos/patternfly/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:400:28)
    at DestroyableTransform.emit (domain.js:532:15)
    at addChunk (/Users/cmichael/repos/patternfly/node_modules/readable-stream/lib/_stream_readable.js:291:12)
    at readableAddChunk (/Users/cmichael/repos/patternfly/node_modules/readable-stream/lib/_stream_readable.js:278:11)
    at DestroyableTransform.Readable.push (/Users/cmichael/repos/patternfly/node_modules/readable-stream/lib/_stream_readable.js:245:10)
    at DestroyableTransform.Transform.push (/Users/cmichael/repos/patternfly/node_modules/readable-stream/lib/_stream_transform.js:148:32)
    at Pumpify.onReadable (/Users/cmichael/repos/patternfly/node_modules/to-through/index.js:25:14)
    at Pumpify.emit (events.js:400:28)
[15:11:32] 'develop' errored after 1.37 h
error Command failed with exit code 1.
```

**Comment by dgutride** [comment]
We fixed it!  https://github.com/patternfly/patternfly/pull/4583
