### ISSUE TITLE
Update outdated dependencies

### ISSUE THREAD

**Issue by mcoker** [patternfly/patternfly#5119]
Running [npm-check-updates](https://www.npmjs.com/package/npm-check-updates) shows a lot of dependencies that are out of date.

Can we update some/all of these? I imagine some would likely need to be part of a major release if they're used to compile CSS - like cssnano (v4 to v5) or sass (minor version bump - might be ok?)

And some likely need to be kept in sync with other repos - like react, maybe prettier, surge?

Just glancing at it, I'd really like to update commitlint, stylelint, and prettier.

cc @jschuler @nicolethoen 

```
$ ncu
Using yarn
Checking /Users/cmichael/repos/patternfly/package.json
[====================] 53/53 100%

 @commitlint/cli                                   ^13.1.0  →       ^17.1.2
 @commitlint/config-conventional                   ^13.1.0  →       ^17.1.0
 @octokit/rest                                    ^16.40.1  →       ^19.0.4
 @patternfly/documentation-framework                1.2.27  →        1.2.30
 cheerio                                       ^1.0.0-rc.3  →  ^1.0.0-rc.12
 commander                                          ^5.1.0  →        ^9.4.0
 cssnano                                            ^4.0.0  →       ^5.1.13
 eslint                                             ^7.0.0  →       ^8.23.1
 eslint-config-standard                            ^16.0.0  →       ^17.0.0
 eslint-config-standard-jsx                        ^10.0.0  →       ^11.0.0
 eslint-config-standard-react                      ^11.0.0  →       ^11.0.1
 eslint-plugin-import                              ^2.24.2  →       ^2.26.0
 eslint-plugin-node                                ^11.0.0  →       ^11.1.0
 eslint-plugin-promise                              ^5.0.0  →        ^6.0.1
 eslint-plugin-react                                ^7.0.0  →       ^7.31.8
 glob                                               ^7.1.2  →        ^8.0.3
 gulp-cli                                           ^2.2.0  →        ^2.3.0
 gulp-iconfont                                     ^10.0.3  →       ^11.0.1
 gulp-postcss                                       ^8.0.0  →        ^9.0.1
 gulp-rename                                        ^1.4.0  →        ^2.0.0
 gulp-sourcemaps                                    ^2.6.5  →        ^3.0.0
 husky                                              ^1.3.1  →        ^8.0.1
 lint-staged                                        ^9.2.5  →       ^13.0.3
 node-plop                                         ^0.18.0  →       ^0.31.0
 postcss                                           ^8.3.11  →       ^8.4.16
 postcss-css-variables                             ^0.13.0  →       ^0.18.0
 postcss-preset-env                                 ^6.7.0  →        ^7.8.2
 prettier                                          ^1.12.1  →        ^2.7.1
 react                                             ^17.0.0  →       ^18.2.0
 react-dom                                         ^17.0.0  →       ^18.2.0
 remark-parse                                       ^8.0.3  →       ^10.0.1
 remark-stringify                                   ^8.1.0  →       ^10.0.2
 sass                                              ^1.34.0  →       ^1.55.0
 sass-graph                                         ^3.0.4  →        ^4.0.1
 stylelint                                         ^14.1.0  →      ^14.12.1
 stylelint-config-recommended-scss                  ^5.0.2  →        ^7.0.0
 stylelint-config-standard                         ^24.0.0  →       ^28.0.0
 stylelint-scss                                     ^4.0.0  →        ^4.3.0
 stylelint-value-no-unknown-custom-properties       ^3.0.0  →        ^4.0.0
 surge                                             ^0.21.3  →       ^0.23.1
 unified                                            ^9.2.0  →       ^10.1.2
 webpack                                           ^4.43.0  →       ^5.74.0

Run ncu -u to upgrade package.json
```

Related - https://github.com/patternfly/patternfly/issues/4816

**Comment by nicolethoen** [comment]
I see no reason why you couldn't try bumping the ones you're interested in bumping to see if you can do so without breaking changes

**Comment by SpyTec** [comment]
Ideally we should update dependencies soon to allow using NodeJS +17 for development

https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/egustavs/patternfly/node_modules/@patternfly/documentation-framework/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/egustavs/patternfly/node_modules/@patternfly/documentation-framework/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/egustavs/patternfly/node_modules/@patternfly/documentation-framework/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/egustavs/patternfly/node_modules/@patternfly/documentation-framework/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/egustavs/patternfly/node_modules/@patternfly/documentation-framework/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/egustavs/patternfly/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/egustavs/patternfly/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/egustavs/patternfly/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/egustavs/patternfly/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/egustavs/patternfly/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/egustavs/patternfly/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
```
